#!/usr/bin/env python3
"""
Semcod Auto-PR Python SDK — uses `gh` CLI for GitHub auth + Semcod API for reDSL.

Auth flow:
  1. Get GitHub token from `gh auth token`
  2. Exchange for Semcod session token via POST /auth/gh-token
  3. Use session token for all Semcod API calls
  4. Use `gh` CLI directly for GitHub operations (branch, commit, PR)
"""

import os
import sys
import json
import time
import base64
import subprocess
import requests
from typing import Dict, List, Optional
from dataclasses import dataclass
from enum import Enum


class TicketType(str, Enum):
    FEATURE = "feature"
    BUGFIX = "bugfix"


@dataclass
class SemcodConfig:
    base_url: str = "http://localhost:8003"
    timeout: int = 30


class GhClient:
    """GitHub CLI wrapper — uses `gh` which has valid token."""

    @staticmethod
    def get_token() -> str:
        result = subprocess.run(["gh", "auth", "token"], capture_output=True, text=True)
        return result.stdout.strip()

    @staticmethod
    def get_user() -> str:
        result = subprocess.run(["gh", "api", "user", "--jq", ".login"], capture_output=True, text=True)
        return result.stdout.strip()

    @staticmethod
    def api(endpoint: str, repo: str = "", method: str = "GET", fields: dict = None) -> dict:
        cmd = ["gh", "api", endpoint]
        if repo:
            cmd += ["--repo", repo]
        if fields and method != "GET":
            for k, v in fields.items():
                cmd += ["-f", f"{k}={v}"]
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
        if result.returncode != 0:
            return {"error": result.stderr.strip()}
        try:
            return json.loads(result.stdout)
        except json.JSONDecodeError:
            return {"raw": result.stdout.strip()}

    @staticmethod
    def list_repos(limit: int = 10) -> List[dict]:
        result = subprocess.run(
            ["gh", "repo", "list", "--limit", str(limit),
             "--json", "nameWithOwner,isPrivate,defaultBranch"],
            capture_output=True, text=True
        )
        try:
            return json.loads(result.stdout)
        except:
            return []

    @staticmethod
    def create_pr(repo: str, branch: str, title: str, body: str = "", base: str = "main") -> dict:
        result = subprocess.run(
            ["gh", "pr", "create", "--repo", repo,
             "--head", branch, "--base", base,
             "--title", title, "--body", body or "Auto-generated by Semcod",
             "--json", "url,number"],
            capture_output=True, text=True
        )
        try:
            return json.loads(result.stdout)
        except:
            return {"error": result.stderr.strip()}

    @staticmethod
    def create_branch(repo: str, branch: str, sha: str) -> bool:
        result = subprocess.run(
            ["gh", "api", f"repos/{repo}/git/refs",
             "-f", f"ref=refs/heads/{branch}", "-f", f"sha={sha}"],
            capture_output=True, text=True
        )
        return result.returncode == 0

    @staticmethod
    def commit_file(repo: str, path: str, content: str, branch: str,
                    message: str = "semcod: auto-commit") -> dict:
        encoded = base64.b64encode(content.encode()).decode()
        result = subprocess.run(
            ["gh", "api", f"repos/{repo}/contents/{path}",
             "-X", "PUT",
             "-f", f"message={message}",
             "-f", f"content={encoded}",
             "-f", f"branch={branch}"],
            capture_output=True, text=True
        )
        try:
            return json.loads(result.stdout)
        except:
            return {"error": result.stderr.strip()}

    @staticmethod
    def create_issue(repo: str, title: str, body: str = "", labels: List[str] = None) -> dict:
        cmd = ["gh", "issue", "create", "--repo", repo,
               "--title", title, "--body", body or "Auto-created by Semcod",
               "--json", "url,number"]
        if labels:
            cmd += ["--label", ",".join(labels)]
        result = subprocess.run(cmd, capture_output=True, text=True)
        try:
            return json.loads(result.stdout)
        except:
            return {"error": result.stderr.strip()}


class SemcodClient:
    """Semcod API client — authenticates via gh token exchange."""

    def __init__(self, config: SemcodConfig):
        self.config = config
        self.session = requests.Session()
        self.session_token = self._authenticate()

    def _authenticate(self) -> str:
        """Exchange gh token for Semcod session token."""
        gh_token = GhClient.get_token()
        if not gh_token:
            return ""
        try:
            resp = requests.post(
                f"{self.config.base_url}/auth/gh-token",
                params={"token": gh_token},
                timeout=self.config.timeout
            )
            if resp.status_code == 200:
                token = resp.json().get("session_token", "")
                self.session.headers.update({
                    "Authorization": f"Bearer {token}",
                    "Content-Type": "application/json"
                })
                return token
        except Exception:
            pass
        return ""

    def _request(self, method: str, endpoint: str, data: dict = None) -> dict:
        if not self.session_token:
            return {"error": "Not authenticated (no Semcod session)"}
        url = f"{self.config.base_url}{endpoint}"
        try:
            response = self.session.request(method=method, url=url, json=data, timeout=self.config.timeout)
            response.raise_for_status()
            return response.json()
        except requests.exceptions.RequestException as e:
            return {"error": str(e)}

    # Tickets
    def create_ticket(self, title: str, repo: str, ticket_type: TicketType,
                      description: str = "", priority: str = "medium") -> dict:
        return self._request("POST", "/api/tickets", {
            "title": title, "repo": repo,
            "ticket_type": ticket_type.value,
            "description": description, "priority": priority
        })

    def get_tickets(self, status: str = None) -> dict:
        endpoint = "/api/tickets" + (f"?status={status}" if status else "")
        return self._request("GET", endpoint)

    def process_ticket(self, ticket_id: str, project_path: str,
                       max_actions: int = 10, dry_run: bool = False) -> dict:
        return self._request("POST", f"/api/tickets/{ticket_id}/process", {
            "project_path": project_path,
            "max_actions": max_actions, "dry_run": dry_run
        })

    def get_ticket_status(self, ticket_id: str) -> dict:
        return self._request("GET", f"/api/tickets/{ticket_id}/status")

    def get_ticket_stats(self) -> dict:
        return self._request("GET", "/api/tickets/stats")

    # ReDSL
    def get_redsl_status(self) -> dict:
        return self._request("GET", "/api/redsl/status")

    def redsl_health(self, project_path: str) -> dict:
        return self._request("POST", "/api/redsl/health", {"project_path": project_path})

    def redsl_refactor(self, project_path: str, max_actions: int = 10, dry_run: bool = True) -> dict:
        return self._request("POST", "/api/redsl/refactor", {
            "project_path": project_path,
            "max_actions": max_actions, "dry_run": dry_run
        })


# ============================================================================
# Examples
# ============================================================================

def example_1_gh_autopr():
    """Create PR using gh CLI directly (no Semcod needed)."""
    print("=== Example 1: gh CLI Auto-PR ===")
    user = GhClient.get_user()
    print(f"GitHub user: {user}")

    repos = GhClient.list_repos(limit=3)
    if not repos:
        print("No repos found")
        return

    repo = repos[0]["nameWithOwner"]
    print(f"Using repo: {repo}")

    repo_info = GhClient.api(f"repos/{repo}")
    default_branch = repo_info.get("default_branch", "main")
    ref = GhClient.api(f"repos/{repo}/git/refs/heads/{default_branch}")
    sha = ref.get("object", {}).get("sha", "")

    if not sha:
        print(f"ERROR: Cannot get SHA for {repo}")
        return

    branch = f"semcod-fix-{int(time.time())}"
    print(f"Creating branch: {branch}")

    if GhClient.create_branch(repo, branch, sha):
        GhClient.commit_file(repo, "semcod_test.txt", "# Semcod Auto-PR test\n", branch)
        pr = GhClient.create_pr(repo, branch, "semcod: auto-fix test")
        print(f"✅ PR created: {pr.get('url', 'ERROR')}")
    else:
        print("ERROR: Failed to create branch")


def example_2_redsl_health():
    """Check health score via Semcod reDSL."""
    print("\n=== Example 2: ReDSL Health Check ===")
    client = SemcodClient(SemcodConfig())

    if not client.session_token:
        print("Semcod not available — showing gh repo info instead")
        repos = GhClient.list_repos(limit=3)
        for r in repos:
            print(f"  {r['nameWithOwner']}")
        return

    status = client.get_redsl_status()
    print(f"ReDSL status: {status}")

    repos = GhClient.list_repos(limit=3)
    for r in repos:
        repo = r["nameWithOwner"]
        project = f"/mnt/project/{repo.replace('/', '-')}"
        health = client.redsl_health(project)
        score = health.get("score", "?")
        print(f"  {repo}: health={score}")


def example_3_ticket_driven():
    """Ticket-driven Auto-PR."""
    print("\n=== Example 3: Ticket-driven Auto-PR ===")
    client = SemcodClient(SemcodConfig())

    if not client.session_token:
        print("Semcod not available — falling back to gh CLI")
        example_1_gh_autopr()
        return

    repos = GhClient.list_repos(limit=1)
    if not repos:
        print("No repos")
        return

    repo = repos[0]["nameWithOwner"]
    ticket = client.create_ticket(
        title="Add pagination to users endpoint",
        repo=repo, ticket_type=TicketType.FEATURE,
        description="Add limit/offset pagination", priority="high"
    )

    if "error" in ticket:
        print(f"Ticket failed: {ticket['error']}")
        example_1_gh_autopr()
        return

    ticket_id = ticket.get("ticket_id", "")
    print(f"Ticket: {ticket_id}")

    project = f"/mnt/project/{repo.replace('/', '-')}"
    result = client.process_ticket(ticket_id, project, max_actions=10)
    print(f"Process result: {json.dumps(result, indent=2)[:300]}")


def example_4_batch_health():
    """Batch health check all repos."""
    print("\n=== Example 4: Batch Health Check ===")
    client = SemcodClient(SemcodConfig())
    repos = GhClient.list_repos(limit=10)

    for r in repos:
        repo = r["nameWithOwner"]
        if client.session_token:
            project = f"/mnt/project/{repo.replace('/', '-')}"
            health = client.redsl_health(project)
            score = health.get("score", "?")
            print(f"  {repo}: health={score}")
        else:
            print(f"  {repo}: (Semcod unavailable)")


def example_5_issue_and_ticket():
    """Create GitHub Issue + Semcod ticket."""
    print("\n=== Example 5: GitHub Issue + Semcod Ticket ===")
    repos = GhClient.list_repos(limit=1)
    if not repos:
        print("No repos")
        return

    repo = repos[0]["nameWithOwner"]
    issue = GhClient.create_issue(repo, "Bug: Auth fails on token expiry",
                                  "Auth fails when JWT expires", ["bug"])
    print(f"GitHub issue: {issue.get('url', 'ERROR')}")

    client = SemcodClient(SemcodConfig())
    if client.session_token:
        ticket = client.create_ticket(
            title="Fix auth token expiry", repo=repo,
            ticket_type=TicketType.BUGFIX,
            description=f"GitHub issue: {issue.get('url', '')}",
            priority="high"
        )
        print(f"Semcod ticket: {ticket}")
    else:
        print("Semcod unavailable — issue created on GitHub only")


def example_6_redsl_preview():
    """ReDSL dry-run preview."""
    print("\n=== Example 6: ReDSL Preview (dry-run) ===")
    client = SemcodClient(SemcodConfig())

    if not client.session_token:
        print("Semcod not available")
        return

    repos = GhClient.list_repos(limit=1)
    if not repos:
        print("No repos")
        return

    repo = repos[0]["nameWithOwner"]
    project = f"/mnt/project/{repo.replace('/', '-')}"
    result = client.redsl_refactor(project, max_actions=5, dry_run=True)
    print(f"Preview for {repo}:")
    print(json.dumps(result, indent=2)[:500])


def main():
    print("=" * 50)
    print("Semcod Auto-PR SDK (gh + reDSL)")
    print("=" * 50)

    user = GhClient.get_user()
    if not user:
        print("ERROR: gh not authenticated. Run: gh auth login")
        sys.exit(1)

    print(f"GitHub user: {user}")

    examples = [
        ("1", "Quick Auto-PR (gh only)", example_1_gh_autopr),
        ("2", "ReDSL Health Check", example_2_redsl_health),
        ("3", "Ticket-driven Auto-PR", example_3_ticket_driven),
        ("4", "Batch Health Check", example_4_batch_health),
        ("5", "GitHub Issue + Ticket", example_5_issue_and_ticket),
        ("6", "ReDSL Preview (dry-run)", example_6_redsl_preview),
    ]

    for num, name, _ in examples:
        print(f"  {num}. {name}")
    print("  0. Run all")
    print("  q. Quit")

    choice = input("\nSelect: ").strip()
    if choice == "q":
        sys.exit(0)
    elif choice == "0":
        for _, _, func in examples:
            try:
                func()
            except Exception as e:
                print(f"Error: {e}")
    elif choice in [e[0] for e in examples]:
        examples[int(choice) - 1][2]()


if __name__ == "__main__":
    main()
