import { useCallback } from "react";

export const TAB_TITLES = {
  share: "Share Content",
  json: "JSON Export",
  llm: "LLM Prompt",
  markdown: "Markdown Report",
  toon: "TOON Format",
};

function recommendationLabel(rec) {
  return rec?.title || rec?.message || rec?.description || "Recommendation";
}

function recommendationLine(rec, index) {
  return `${index + 1}. ${recommendationLabel(rec)} (Priority: ${rec.priority})`;
}

function markdownRecommendationLine(rec, index) {
  return `${index + 1}. **${recommendationLabel(rec)}** (Priority: ${rec.priority})`;
}

function toonRecommendationLine(rec, index) {
  return `  [${index + 1}] ${rec.priority.toUpperCase()}: ${recommendationLabel(rec)}`;
}

function filesContent(files) {
  if (!files || files.length === 0) {
    return "# No file contents available";
  }

  return files
    .map((file) => `### ${file.path}\n\`\`\`\n${file.content || ""}\n\`\`\``)
    .join("\n\n");
}

export function buildMetricsExportData(data, repoName, isSandbox) {
  return {
    repository: repoName,
    health_score: data.health_score,
    grade: data.grade,
    stats: data.stats,
    metrics: data.metrics,
    recommendations: data.recommendations,
    completed: data.completed,
    sandbox: isSandbox,
  };
}

export function buildPromptText(data, repoName) {
  return `# Code Analysis Report - ${repoName}
# Generated on: ${new Date().toISOString()}
# Health Score: ${data.health_score}% (${data.grade})

## Metrics
- Files: ${data.stats.total_files}
- Lines of Code: ${data.stats.total_lines}
- Languages: ${JSON.stringify(data.stats.languages, null, 2)}

## Complexity
- Average CC: ${data.metrics.complexity.cc_avg.toFixed(2)}
- Functions: ${data.metrics.complexity.functions}

## Duplication
- Groups: ${data.metrics.duplication.duplication_groups}
- Recoverable Lines: ${data.metrics.duplication.recoverable_lines}

## Quality
- Passed: ${data.metrics.quality.passed}
- Warnings: ${data.metrics.quality.warnings}
- Errors: ${data.metrics.quality.errors}

## Recommendations
${data.recommendations.map(recommendationLine).join("\n")}

## File Contents
${filesContent(data.files)}

---
Use this data to analyze code quality and suggest refactoring improvements via LLM.`;
}

export function buildMarkdownText(data, repoName) {
  return `# Code Analysis Report - ${repoName}

**Generated on:** ${new Date().toISOString()}  
**Health Score:** ${data.health_score}% (${data.grade})

## Metrics

| Metric | Value |
|--------|-------|
| Files | ${data.stats.total_files} |
| Lines of Code | ${data.stats.total_lines} |
| Languages | ${Object.entries(data.stats.languages).map(([lang, count]) => `${lang}: ${count}`).join(", ")} |

## Complexity

| Metric | Value |
|--------|-------|
| Average CC | ${data.metrics.complexity.cc_avg.toFixed(2)} |
| Functions | ${data.metrics.complexity.functions} |

## Duplication

| Metric | Value |
|--------|-------|
| Groups | ${data.metrics.duplication.duplication_groups} |
| Recoverable Lines | ${data.metrics.duplication.recoverable_lines} |

## Quality

| Metric | Value |
|--------|-------|
| Passed | ${data.metrics.quality.passed} |
| Warnings | ${data.metrics.quality.warnings} |
| Errors | ${data.metrics.quality.errors} |

## Recommendations

${data.recommendations.map(markdownRecommendationLine).join("\n")}

---

*Use this data to analyze code quality and suggest refactoring improvements via LLM.*  
*Generated by [Semcod](https://semcod.com) - Code Health Analysis Tool*`;
}

export function buildToonText(data, repoName) {
  return `# scan result | ${repoName} | ${new Date().toISOString().split("T")[0]}

HEALTH:
  score: ${data.health_score}
  grade: ${data.grade}

STATS:
  files: ${data.stats.total_files}
  lines: ${data.stats.total_lines}
  languages: ${JSON.stringify(data.stats.languages)}

COMPLEXITY:
  avg_cc: ${data.metrics.complexity.cc_avg.toFixed(2)}
  functions: ${data.metrics.complexity.functions}

DUPLICATION:
  groups: ${data.metrics.duplication.duplication_groups}
  recoverable_lines: ${data.metrics.duplication.recoverable_lines}

QUALITY:
  passed: ${data.metrics.quality.passed}
  warnings: ${data.metrics.quality.warnings}
  errors: ${data.metrics.quality.errors}

RECOMMENDATIONS[${data.recommendations.length}]:
${data.recommendations.map(toonRecommendationLine).join("\n")}`;
}

export function buildShareText(data, repoName) {
  return `🔍 Sprawdziłem jakość kodu repozytorium ${repoName}!

📊 Wynik: ${data.grade} (${data.health_score}%)
📁 ${data.stats.total_files} plików
📝 ${(data.stats.total_lines / 1000).toFixed(1)}k linii kodu

Analiza przez @semcod_dev`;
}

export function getResultTabContent(tab, data, repoName, isSandbox) {
  if (tab === "json") {
    return JSON.stringify(buildMetricsExportData(data, repoName, isSandbox), null, 2);
  }
  if (tab === "llm") {
    return buildPromptText(data, repoName);
  }
  if (tab === "markdown") {
    return buildMarkdownText(data, repoName);
  }
  if (tab === "toon") {
    return buildToonText(data, repoName);
  }
  if (tab === "share") {
    return buildShareText(data, repoName);
  }
  return "";
}

function downloadContent(content, filename, type) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function useDownloads(data, repoName, isSandbox) {
  const handleDownloadMetrics = useCallback(() => {
    downloadContent(
      JSON.stringify(buildMetricsExportData(data, repoName, isSandbox), null, 2),
      `${repoName.replace("/", "-")}-json.json`,
      "application/json"
    );
  }, [data, repoName, isSandbox]);

  const handleDownloadPrompt = useCallback(() => {
    downloadContent(
      buildPromptText(data, repoName),
      `${repoName.replace("/", "-")}-llm.txt`,
      "text/plain"
    );
  }, [data, repoName]);

  const handleDownloadMarkdown = useCallback(() => {
    downloadContent(
      buildMarkdownText(data, repoName),
      `${repoName.replace("/", "-")}-markdown.md`,
      "text/markdown"
    );
  }, [data, repoName]);

  const handleDownloadToon = useCallback(() => {
    downloadContent(
      buildToonText(data, repoName),
      `${repoName.replace("/", "-")}-toon.txt`,
      "text/plain"
    );
  }, [data, repoName]);

  const handleGenericDownload = useCallback((tab) => {
    if (tab === 'json') handleDownloadMetrics();
    else if (tab === 'llm') handleDownloadPrompt();
    else if (tab === 'markdown') handleDownloadMarkdown();
    else if (tab === 'toon') handleDownloadToon();
  }, [handleDownloadMetrics, handleDownloadPrompt, handleDownloadMarkdown, handleDownloadToon]);

  return {
    handleGenericDownload,
  };
}
