#!/bin/bash
# Auto-PR Examples — uses `gh` for GitHub + Semcod REST API for reDSL/tickets
# Auth: exchange gh token for Semcod session token via POST /auth/gh-token

SEMCOD_URL="http://localhost:8003"
REPO="semcod/vallm"  # Change to your repo

# ============================================================================
# STEP 0: Get Semcod session token from gh token
# ============================================================================
echo "=== Step 0: Authenticate via gh token ==="

GH_TOKEN=$(gh auth token)
if [ -z "$GH_TOKEN" ]; then
  echo "ERROR: gh not authenticated. Run: gh auth login"
  exit 1
fi

echo "gh token obtained ✓"

# Exchange gh token for Semcod session token
SEMCOD_SESSION=$(curl -s -X POST "${SEMCOD_URL}/auth/gh-token?token=${GH_TOKEN}" | python3 -c "import sys,json; print(json.load(sys.stdin).get('session_token',''))" 2>/dev/null)

if [ -z "$SEMCOD_SESSION" ]; then
  echo "ERROR: Failed to get Semcod session token"
  echo "Make sure backend is running: docker compose up -d backend"
  exit 1
fi

echo "Semcod session token obtained ✓"
echo ""

# Helper for Semcod API calls
semcod() {
  local method=$1 endpoint=$2 data=$3
  curl -s -X "${method}" \
    "${SEMCOD_URL}${endpoint}" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer ${SEMCOD_SESSION}" \
    ${data:+-d "$data"}
}

# ============================================================================
# Example 1: Quick Auto-PR using gh directly
# ============================================================================
echo "=== Example 1: Create PR with gh CLI ==="

BRANCH="semcod-fix-$(date +%s)"

# Get default branch SHA
SHA=$(gh api repos/${REPO}/git/refs/heads/main --jq '.object.sha' 2>&1)
echo "Base SHA: ${SHA:0:8}"

# Create branch
gh api repos/${REPO}/git/refs -f ref="refs/heads/${BRANCH}" -f sha="${SHA}" >/dev/null 2>&1
echo "Branch created: ${BRANCH}"

# Commit a file
gh api repos/${REPO}/contents/semcod_test.txt \
  -X PUT \
  -f message="semcod: auto-fix test commit" \
  -f content="$(echo -n '# Semcod Auto-PR test\n# Generated by examples/rest-api' | base64)" \
  -f branch="${BRANCH}" >/dev/null 2>&1
echo "File committed"

# Create PR
PR_URL=$(gh pr create --repo ${REPO} --head ${BRANCH} --base main \
  --title "semcod: auto-fix test" \
  --body "Automated PR created via \`gh\` CLI + Semcod examples." \
  --json url --jq '.url' 2>&1)
echo "✅ PR created: ${PR_URL}"

# ============================================================================
# Example 2: Create ticket via Semcod API + process with reDSL
# ============================================================================
echo ""
echo "=== Example 2: Ticket-driven Auto-PR ==="

# Create ticket
TICKET_RESP=$(semcod "POST" "/api/tickets" "{
  \"title\": \"Add pagination to user list\",
  \"repo\": \"${REPO}\",
  \"ticket_type\": \"feature\",
  \"description\": \"The /api/users endpoint returns all users. Add limit/offset pagination.\",
  \"priority\": \"high\"
}")

TICKET_ID=$(echo "${TICKET_RESP}" | python3 -c "import sys,json; print(json.load(sys.stdin).get('ticket_id',''))" 2>/dev/null)
echo "Ticket response: ${TICKET_RESP}" | head -3
echo "Ticket ID: ${TICKET_ID}"

if [ -n "${TICKET_ID}" ] && [ "${TICKET_ID}" != "" ]; then
  # Process ticket with reDSL
  PROCESS_RESP=$(semcod "POST" "/api/tickets/${TICKET_ID}/process" "{
    \"project_path\": \"/mnt/project/${REPO//\//-}\",
    \"max_actions\": 10,
    \"dry_run\": false,
    \"auto_create_pr\": true
  }")
  echo "Process response: ${PROCESS_RESP}" | python3 -m json.tool 2>/dev/null | head -10
fi

# ============================================================================
# Example 3: Get ticket statistics
# ============================================================================
echo ""
echo "=== Example 3: Ticket statistics ==="

semcod "GET" "/api/tickets/stats" | python3 -m json.tool 2>/dev/null

# ============================================================================
# Example 4: List tickets
# ============================================================================
echo ""
echo "=== Example 4: List tickets ==="

semcod "GET" "/api/tickets" | python3 -m json.tool 2>/dev/null | head -20

# ============================================================================
# Example 5: ReDSL health score
# ============================================================================
echo ""
echo "=== Example 5: ReDSL health score ==="

semcod "POST" "/api/redsl/health" "{\"project_path\": \"/mnt/project/${REPO//\//-}\"}" | python3 -m json.tool 2>/dev/null | head -15

# ============================================================================
# Example 6: ReDSL dry-run preview
# ============================================================================
echo ""
echo "=== Example 6: ReDSL refactor preview (dry-run) ==="

semcod "POST" "/api/redsl/refactor" "{
  \"project_path\": \"/mnt/project/${REPO//\//-}\",
  \"max_actions\": 5,
  \"dry_run\": true
}" | python3 -m json.tool 2>/dev/null | head -20

# ============================================================================
# Example 7: Create GitHub Issue + Semcod ticket
# ============================================================================
echo ""
echo "=== Example 7: GitHub Issue → Semcod ticket ==="

# Create GitHub issue
ISSUE_URL=$(gh issue create --repo ${REPO} \
  --title "Bug: Auth fails on token expiry" \
  --body "Authentication fails when the JWT token expires.\n\nSteps:\n1. Login\n2. Wait for token expiry\n3. API call fails with 401" \
  --label "bug" \
  --json url --jq '.url' 2>&1)

echo "GitHub issue: ${ISSUE_URL}"

# Create Semcod ticket linked to the issue
semcod "POST" "/api/tickets" "{
  \"title\": \"Fix auth token expiry\",
  \"repo\": \"${REPO}\",
  \"ticket_type\": \"bugfix\",
  \"description\": \"GitHub issue: ${ISSUE_URL}\",
  \"priority\": \"high\"
}" | python3 -m json.tool 2>/dev/null

# ============================================================================
# Example 8: ReDSL badge for README
# ============================================================================
echo ""
echo "=== Example 8: ReDSL badge ==="

BADGE_URL="${SEMCOD_URL}/api/redsl/badge/${REPO%%/*}/${REPO##*/}"
echo "Badge URL: ${BADGE_URL}"
echo ""
echo "Markdown for README.md:"
echo "[![ReDSL Health](${BADGE_URL})](https://semcod.com)"

