"""SQLAlchemy ORM database for scan history persistence."""

from db_session import SessionLocal, init_db as init_orm_db

# Import tickets ORM (direct ORM functions)
from .tickets_orm import (
    create_ticket,
    get_tickets_by_tenant,
    get_ticket,
    update_ticket,
    delete_ticket,
    get_tickets_by_repo,
    get_ticket_stats,
    search_tickets,
    get_tickets_requiring_action,
    update_ticket_pr_info,
    update_ticket_redsl_results,
    mark_ticket_error,
)

# Import wrapper functions (session-aware, backward compatible)
from .wrappers import (
    save_scan,
    get_recent_scans,
    get_repo_scans,
    get_total_scan_count,
    save_audit_result,
    get_audit_result,
    save_badge_cache,
    get_badge_cache,
    upsert_user,
    get_user_by_github_id,
    get_user_by_id,
    get_subscription,
    upsert_subscription,
    increment_scan_count,
    get_or_create_tenant,
    get_tenant_by_id,
    update_tenant_plan,
    get_or_create_repository,
    get_tenant_repositories,
    get_repository_by_full_name,
    create_installation,
    get_installation,
    get_tenant_installations,
    delete_installation,
    update_installation_scan,
    queue_event,
    get_pending_events,
    update_event_status,
    create_benchmark_case,
    get_benchmark_cases,
    get_benchmark_case,
    update_benchmark_case,
    create_benchmark_event,
    get_benchmark_events,
    upsert_recommendation_feedback,
    get_feedback_for_case,
    get_benchmark_summary,
)

# Use ORM initialization
init_db = init_orm_db

__all__ = [
    "init_db",
    "SessionLocal",
    "save_scan",
    "get_recent_scans",
    "get_repo_scans",
    "get_total_scan_count",
    "save_audit_result",
    "get_audit_result",
    "save_badge_cache",
    "get_badge_cache",
    "upsert_user",
    "get_user_by_github_id",
    "get_user_by_id",
    "get_subscription",
    "upsert_subscription",
    "increment_scan_count",
    "get_or_create_tenant",
    "get_tenant_by_id",
    "update_tenant_plan",
    "get_or_create_repository",
    "get_tenant_repositories",
    "get_repository_by_full_name",
    "create_installation",
    "get_installation",
    "get_tenant_installations",
    "delete_installation",
    "update_installation_scan",
    "queue_event",
    "get_pending_events",
    "update_event_status",
    "create_benchmark_case",
    "get_benchmark_cases",
    "get_benchmark_case",
    "update_benchmark_case",
    "create_benchmark_event",
    "get_benchmark_events",
    "upsert_recommendation_feedback",
    "get_feedback_for_case",
    "get_benchmark_summary",
    # Tickets
    "create_ticket",
    "get_tickets_by_tenant",
    "get_ticket",
    "update_ticket",
    "delete_ticket",
    "get_tickets_by_repo",
    "get_ticket_stats",
    "search_tickets",
    "get_tickets_requiring_action",
    "update_ticket_pr_info",
    "update_ticket_redsl_results",
    "mark_ticket_error",
]

# Initialize database on import
init_db()
