flowchart TD
    backend__database["backend.database<br/>7 funcs"]
    backend__routers["backend.routers<br/>40 funcs"]
    backend__sample_projects["backend.sample_projects<br/>1 funcs"]
    backend__scripts["backend.scripts<br/>1 funcs"]
    backend__services["backend.services<br/>6 funcs"]
    backend__routers ==>|21| backend__services
    backend__routers ==>|12| backend__database
    backend__scripts -->|1| backend__sample_projects
    backend__scripts -->|1| backend__routers
