import { C, DEMO_AUDIT } from "../../constants";
import { GradeCircle, MetricCard, RecommendationCard, LanguageBar } from "../ui";
import { getShareUrls } from "../../utils/share";
import { useState } from "react";

export function ResultPhase({ audit, selectedRepo, isSandbox, reset }) {
  const data = audit || DEMO_AUDIT;
  const repoName = selectedRepo?.full_name || selectedRepo?.name || "unknown/repo";
  const shareUrls = getShareUrls(data, repoName);
  const [activeTab, setActiveTab] = useState(null);
  
  const handleShare = (platform) => {
    window.open(shareUrls[platform], '_blank', 'width=600,height=400');
  };

  const handleDownloadMetrics = () => {
    const metricsData = {
      repository: repoName,
      health_score: data.health_score,
      grade: data.grade,
      stats: data.stats,
      metrics: data.metrics,
      recommendations: data.recommendations,
      completed: data.completed,
      sandbox: isSandbox,
    };
    
    const blob = new Blob([JSON.stringify(metricsData, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${repoName.replace('/', '-')}-metrics.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleDownloadPrompt = () => {
    const filesContent = data.files && data.files.length > 0
      ? data.files.map(f => `### ${f.path}\n\`\`\`\n${f.content || ''}\n\`\`\``).join('\n\n')
      : '# No file contents available';

    const promptText = `# Code Analysis Report - ${repoName}
# Generated on: ${new Date().toISOString()}
# Health Score: ${data.health_score}% (${data.grade})

## Metrics
- Files: ${data.stats.total_files}
- Lines of Code: ${data.stats.total_lines}
- Languages: ${JSON.stringify(data.stats.languages, null, 2)}

## Complexity
- Average CC: ${data.metrics.complexity.cc_avg.toFixed(2)}
- Functions: ${data.metrics.complexity.functions}

## Duplication
- Groups: ${data.metrics.duplication.duplication_groups}
- Recoverable Lines: ${data.metrics.duplication.recoverable_lines}

## Quality
- Passed: ${data.metrics.quality.passed}
- Warnings: ${data.metrics.quality.warnings}
- Errors: ${data.metrics.quality.errors}

## Recommendations
${data.recommendations.map((rec, i) => `${i + 1}. ${rec.message} (Priority: ${rec.priority})`).join('\n')}

## File Contents
${filesContent}

---
Use this data to analyze code quality and suggest refactoring improvements via LLM.`;

    const blob = new Blob([promptText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${repoName.replace('/', '-')}-llm-prompt.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleDownloadMarkdown = () => {
    const markdownText = `# Code Analysis Report - ${repoName}

**Generated on:** ${new Date().toISOString()}  
**Health Score:** ${data.health_score}% (${data.grade})

## Metrics

| Metric | Value |
|--------|-------|
| Files | ${data.stats.total_files} |
| Lines of Code | ${data.stats.total_lines} |
| Languages | ${Object.entries(data.stats.languages).map(([lang, count]) => `${lang}: ${count}`).join(', ')} |

## Complexity

| Metric | Value |
|--------|-------|
| Average CC | ${data.metrics.complexity.cc_avg.toFixed(2)} |
| Functions | ${data.metrics.complexity.functions} |

## Duplication

| Metric | Value |
|--------|-------|
| Groups | ${data.metrics.duplication.duplication_groups} |
| Recoverable Lines | ${data.metrics.duplication.recoverable_lines} |

## Quality

| Metric | Value |
|--------|-------|
| Passed | ${data.metrics.quality.passed} |
| Warnings | ${data.metrics.quality.warnings} |
| Errors | ${data.metrics.quality.errors} |

## Recommendations

${data.recommendations.map((rec, i) => `${i + 1}. **${rec.message}** (Priority: ${rec.priority})`).join('\n')}

---

*Use this data to analyze code quality and suggest refactoring improvements via LLM.*  
*Generated by [Semcod](https://semcod.com) - Code Health Analysis Tool*`;
    
    const blob = new Blob([markdownText], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${repoName.replace('/', '-')}-report.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleDownloadToon = () => {
    const toonText = `# scan result | ${repoName} | ${new Date().toISOString().split('T')[0]}

HEALTH:
  score: ${data.health_score}
  grade: ${data.grade}

STATS:
  files: ${data.stats.total_files}
  lines: ${data.stats.total_lines}
  languages: ${JSON.stringify(data.stats.languages)}

COMPLEXITY:
  avg_cc: ${data.metrics.complexity.cc_avg.toFixed(2)}
  functions: ${data.metrics.complexity.functions}

DUPLICATION:
  groups: ${data.metrics.duplication.duplication_groups}
  recoverable_lines: ${data.metrics.duplication.recoverable_lines}

QUALITY:
  passed: ${data.metrics.quality.passed}
  warnings: ${data.metrics.quality.warnings}
  errors: ${data.metrics.quality.errors}

RECOMMENDATIONS[${data.recommendations.length}]:
${data.recommendations.map((rec, i) => `  [${i + 1}] ${rec.priority.toUpperCase()}: ${rec.message}`).join('\n')}
`;

    const blob = new Blob([toonText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${repoName.replace('/', '-')}-result.toon.yaml`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const getTabContent = (tab) => {
    const filesContent = data.files && data.files.length > 0
      ? data.files.map(f => `### ${f.path}\n\`\`\`\n${f.content || ''}\n\`\`\``).join('\n\n')
      : '# No file contents available';

    switch (tab) {
      case 'json':
        return JSON.stringify({
          repository: repoName,
          health_score: data.health_score,
          grade: data.grade,
          stats: data.stats,
          metrics: data.metrics,
          recommendations: data.recommendations,
          completed: data.completed,
          sandbox: isSandbox,
        }, null, 2);
      case 'llm':
        return `# Code Analysis Report - ${repoName}
# Generated on: ${new Date().toISOString()}
# Health Score: ${data.health_score}% (${data.grade})

## Metrics
- Files: ${data.stats.total_files}
- Lines of Code: ${data.stats.total_lines}
- Languages: ${JSON.stringify(data.stats.languages, null, 2)}

## Complexity
- Average CC: ${data.metrics.complexity.cc_avg.toFixed(2)}
- Functions: ${data.metrics.complexity.functions}

## Duplication
- Groups: ${data.metrics.duplication.duplication_groups}
- Recoverable Lines: ${data.metrics.duplication.recoverable_lines}

## Quality
- Passed: ${data.metrics.quality.passed}
- Warnings: ${data.metrics.quality.warnings}
- Errors: ${data.metrics.quality.errors}

## Recommendations
${data.recommendations.map((rec, i) => `${i + 1}. ${rec.message} (Priority: ${rec.priority})`).join('\n')}

## File Contents
${filesContent}`;
      case 'markdown':
        return `# Code Analysis Report - ${repoName}

**Generated on:** ${new Date().toISOString()}
**Health Score:** ${data.health_score}% (${data.grade})

## Metrics

| Metric | Value |
|--------|-------|
| Files | ${data.stats.total_files} |
| Lines of Code | ${data.stats.total_lines} |
| Languages | ${Object.entries(data.stats.languages).map(([lang, count]) => `${lang}: ${count}`).join(', ')} |

## Complexity

| Metric | Value |
|--------|-------|
| Average CC | ${data.metrics.complexity.cc_avg.toFixed(2)} |
| Functions | ${data.metrics.complexity.functions} |

## Duplication

| Metric | Value |
|--------|-------|
| Groups | ${data.metrics.duplication.duplication_groups} |
| Recoverable Lines | ${data.metrics.duplication.recoverable_lines} |

## Quality

| Metric | Value |
|--------|-------|
| Passed | ${data.metrics.quality.passed} |
| Warnings | ${data.metrics.quality.warnings} |
| Errors | ${data.metrics.quality.errors} |

## Recommendations

${data.recommendations.map((rec, i) => `${i + 1}. **${rec.message}** (Priority: ${rec.priority})`).join('\n')}

---

*Use this data to analyze code quality and suggest refactoring improvements via LLM.*
*Generated by [Semcod](https://semcod.com) - Code Health Analysis Tool*`;
      case 'toon':
        return `# scan result | ${repoName} | ${new Date().toISOString().split('T')[0]}

HEALTH:
  score: ${data.health_score}
  grade: ${data.grade}

STATS:
  files: ${data.stats.total_files}
  lines: ${data.stats.total_lines}
  languages: ${JSON.stringify(data.stats.languages)}

COMPLEXITY:
  avg_cc: ${data.metrics.complexity.cc_avg.toFixed(2)}
  functions: ${data.metrics.complexity.functions}

DUPLICATION:
  groups: ${data.metrics.duplication.duplication_groups}
  recoverable_lines: ${data.metrics.duplication.recoverable_lines}

QUALITY:
  passed: ${data.metrics.quality.passed}
  warnings: ${data.metrics.quality.warnings}
  errors: ${data.metrics.quality.errors}

RECOMMENDATIONS[${data.recommendations.length}]:
${data.recommendations.map((rec, i) => `  [${i + 1}] ${rec.priority.toUpperCase()}: ${rec.message}`).join('\n')}`;
      case 'share':
        const shareText = `🔍 Sprawdziłem jakość kodu repozytorium ${repoName}!

📊 Wynik: ${data.grade} (${data.health_score}%)
📁 ${data.stats.total_files} plików
📝 ${(data.stats.total_lines / 1000).toFixed(1)}k linii kodu

Analiza przez @semcod_dev`;
        return shareText;
      default:
        return '';
    }
  };

  return (
    <div>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 28 }}>
        <div>
          <h2 style={{ fontSize: 22, fontWeight: 700 }}>
            <span style={{ color: C.fg3 }}>Report:</span> {selectedRepo?.full_name}
            {isSandbox && (
              <span style={{
                display: "inline-block",
                marginLeft: 12,
                fontSize: 11,
                color: C.amber,
                background: `${C.amber}15`,
                padding: "2px 8px",
                borderRadius: 4,
                fontWeight: 500,
              }}>🔒 Sandbox</span>
            )}
          </h2>
          {isSandbox && !data.error && (
            <p style={{ fontSize: 13, color: C.fg3, marginTop: 4 }}>
              Public repository analyzed without authentication.
              <a href="#" onClick={(e) => { e.preventDefault(); reset(); }} style={{ color: C.cyan, marginLeft: 8 }}>Install GitHub App for PR reviews →</a>
            </p>
          )}
        </div>
        <div style={{ display: "flex", gap: 8, flexWrap: "wrap", alignItems: "center" }}>
          <button
            onClick={() => setActiveTab(activeTab === 'share' ? null : 'share')}
            style={{
              background: activeTab === 'share' ? "#1DA1F2" : "#1DA1F220",
              border: activeTab === 'share' ? "none" : "1px solid #1DA1F2",
              color: activeTab === 'share' ? "#fff" : "#1DA1F2",
              cursor: "pointer", fontSize: 13, padding: "8px 16px", borderRadius: 8,
              fontFamily: "inherit", fontWeight: 600,
            }}
          >𝕏 Share</button>
          <button
            onClick={() => setActiveTab(activeTab === 'json' ? null : 'json')}
            style={{
              background: activeTab === 'json' ? "#8B5CF6" : "#8B5CF620",
              border: activeTab === 'json' ? "none" : "1px solid #8B5CF6",
              color: activeTab === 'json' ? "#fff" : "#8B5CF6",
              cursor: "pointer", fontSize: 13, padding: "8px 16px", borderRadius: 8,
              fontFamily: "inherit", fontWeight: 600,
            }}
          >📊 JSON</button>
          <button
            onClick={() => setActiveTab(activeTab === 'llm' ? null : 'llm')}
            style={{
              background: activeTab === 'llm' ? "#10B981" : "#10B98120",
              border: activeTab === 'llm' ? "none" : "1px solid #10B981",
              color: activeTab === 'llm' ? "#fff" : "#10B981",
              cursor: "pointer", fontSize: 13, padding: "8px 16px", borderRadius: 8,
              fontFamily: "inherit", fontWeight: 600,
            }}
          >🤖 LLM Prompt</button>
          <button
            onClick={() => setActiveTab(activeTab === 'markdown' ? null : 'markdown')}
            style={{
              background: activeTab === 'markdown' ? "#6366F1" : "#6366F120",
              border: activeTab === 'markdown' ? "none" : "1px solid #6366F1",
              color: activeTab === 'markdown' ? "#fff" : "#6366F1",
              cursor: "pointer", fontSize: 13, padding: "8px 16px", borderRadius: 8,
              fontFamily: "inherit", fontWeight: 600,
            }}
          >📝 Markdown</button>
          <button
            onClick={() => setActiveTab(activeTab === 'toon' ? null : 'toon')}
            style={{
              background: activeTab === 'toon' ? "#F59E0B" : "#F59E0B20",
              border: activeTab === 'toon' ? "none" : "1px solid #F59E0B",
              color: activeTab === 'toon' ? "#fff" : "#F59E0B",
              cursor: "pointer", fontSize: 13, padding: "8px 16px", borderRadius: 8,
              fontFamily: "inherit", fontWeight: 600,
            }}
          >📄 TOON</button>
          <button onClick={reset} style={{
            background: C.bg3, border: `1px solid ${C.border}`, color: C.fg2,
            cursor: "pointer", fontSize: 13, padding: "8px 16px", borderRadius: 8,
            fontFamily: "inherit",
          }}>New audit</button>
        </div>
      </div>

      {activeTab && (
        <div style={{
          background: C.bg2,
          border: `1px solid ${C.border}`,
          borderRadius: 8,
          padding: 16,
          marginBottom: 28,
        }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 12 }}>
            <h4 style={{ margin: 0, fontSize: 14, fontWeight: 600, color: C.fg2 }}>
              {activeTab === 'share' && 'Share Content'}
              {activeTab === 'json' && 'JSON Export'}
              {activeTab === 'llm' && 'LLM Prompt'}
              {activeTab === 'markdown' && 'Markdown Report'}
              {activeTab === 'toon' && 'TOON Format'}
            </h4>
            <div style={{ display: "flex", gap: 8 }}>
              {activeTab !== 'share' && (
                <button
                  onClick={() => {
                    const content = getTabContent(activeTab);
                    const blob = new Blob([content], { type: 'text/plain' });
                    const url = URL.createObjectURL(blob);
                    const a = document.createElement('a');
                    a.href = url;
                    a.download = `${repoName.replace('/', '-')}-${activeTab}.${activeTab === 'json' ? 'json' : activeTab === 'markdown' ? 'md' : 'txt'}`;
                    document.body.appendChild(a);
                    a.click();
                    document.body.removeChild(a);
                    URL.revokeObjectURL(url);
                  }}
                  style={{
                    background: C.cyan, border: "none", color: "#fff",
                    cursor: "pointer", fontSize: 12, padding: "6px 12px", borderRadius: 6,
                    fontFamily: "inherit", fontWeight: 500,
                  }}
                >Download</button>
              )}
              {activeTab === 'share' && (
                <>
                  <button
                    onClick={() => handleShare('twitter')}
                    style={{
                      background: "#1DA1F2", border: "none", color: "#fff",
                      cursor: "pointer", fontSize: 12, padding: "6px 12px", borderRadius: 6,
                      fontFamily: "inherit", fontWeight: 500,
                    }}
                  >𝕏</button>
                  <button
                    onClick={() => handleShare('linkedin')}
                    style={{
                      background: "#0077B5", border: "none", color: "#fff",
                      cursor: "pointer", fontSize: 12, padding: "6px 12px", borderRadius: 6,
                      fontFamily: "inherit", fontWeight: 500,
                    }}
                  >in</button>
                  <button
                    onClick={() => handleShare('bluesky')}
                    style={{
                      background: "#0085FF", border: "none", color: "#fff",
                      cursor: "pointer", fontSize: 12, padding: "6px 12px", borderRadius: 6,
                      fontFamily: "inherit", fontWeight: 500,
                    }}
                  >🦋</button>
                </>
              )}
              <button
                onClick={() => {
                  const content = getTabContent(activeTab);
                  navigator.clipboard.writeText(content);
                }}
                style={{
                  background: C.fg3, border: "none", color: "#fff",
                  cursor: "pointer", fontSize: 12, padding: "6px 12px", borderRadius: 6,
                  fontFamily: "inherit", fontWeight: 500,
                }}
              >Copy</button>
              <button
                onClick={() => setActiveTab(null)}
                style={{
                  background: "transparent", border: `1px solid ${C.border}`, color: C.fg2,
                  cursor: "pointer", fontSize: 12, padding: "6px 12px", borderRadius: 6,
                  fontFamily: "inherit",
                }}
              >Close</button>
            </div>
          </div>
          <div style={{
            background: C.bg1,
            border: `1px solid ${C.border}`,
            borderRadius: 6,
            padding: 12,
            maxHeight: 400,
            overflow: "auto",
            fontSize: 12,
            fontFamily: "monospace",
            whiteSpace: "pre-wrap",
            wordBreak: "break-word",
            color: C.fg1,
          }}>
            {getTabContent(activeTab)}
          </div>
        </div>
      )}

      {data.error && (
        <div style={{
          background: `${C.red}15`, border: `1px solid ${C.red}`, borderRadius: 10,
          padding: "20px 24px", marginBottom: 28,
        }}>
          <div style={{ fontSize: 16, fontWeight: 600, color: C.red, marginBottom: 8 }}>
            ⚠️ Analysis failed
          </div>
          <p style={{ fontSize: 14, color: C.fg2, margin: 0 }}>{data.error}</p>
          {isSandbox && (
            <p style={{ fontSize: 13, color: C.fg3, marginTop: 12 }}>
              Make sure the repository is public and accessible.
              Private repositories require GitHub authentication.
            </p>
          )}
        </div>
      )}

      {!data.error && (
        <>
          <div style={{ display: "flex", gap: 20, alignItems: "center", flexWrap: "wrap", marginBottom: 32 }}>
            <GradeCircle grade={data.grade} score={data.health_score} />
            <div style={{ display: "flex", gap: 10, flexWrap: "wrap", flex: 1 }}>
              <MetricCard icon="📁" label="FILES" value={data.stats.total_files} sub={`${(data.stats.total_lines / 1000).toFixed(1)}k lines`} />
              <MetricCard icon="🔬" label="CC̄" value={data.metrics.complexity.cc_avg.toFixed(1)} sub={`${data.metrics.complexity.functions} functions`} />
              <MetricCard icon="🔁" label="DUPLICATES" value={data.metrics.duplication.duplication_groups} sub={`${data.metrics.duplication.recoverable_lines} lines recoverable`} />
              <MetricCard icon="✅" label="QUALITY" value={`${data.metrics.quality.passed}/${data.metrics.quality.passed + data.metrics.quality.errors}`} sub={`${data.metrics.quality.warnings} warnings`} />
            </div>
          </div>

          <LanguageBar languages={data.stats.languages} />

          <h3 style={{ fontSize: 16, fontWeight: 700, marginBottom: 16 }}>Recommendations</h3>
          <div style={{ display: "grid", gap: 12 }}>
            {data.recommendations.map((rec, i) => (
              <RecommendationCard key={i} rec={rec} index={i} />
            ))}
          </div>
        </>
      )}
    </div>
  );
}
